#version of the docker compose object
#version: "3.9"

services:
  app:
    build:
      context: .
      # if we run docker compose which we only do for development, make dev = True
      # we do this so we can also use the requirements.dev stuff too.
      args:
        DEV: true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
